name: Build FreeType + HarfBuzz + PNG/Zlib for Android (Sequential ABIs, fPIC, 16KB page)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-font-libs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y git cmake ninja-build wget tar

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26d
        add-to-path: true

    - name: Fetch sources
      run: |
        git clone --depth=1 https://github.com/freetype/freetype.git freetype
        git clone --depth=1 https://github.com/harfbuzz/harfbuzz.git harfbuzz
        git clone --depth=1 https://github.com/madler/zlib.git zlib
        wget https://download.sourceforge.net/libpng/libpng-1.6.40.tar.gz -O libpng.tar.gz
        tar xf libpng.tar.gz

    - name: Build for all ABIs
      run: |
        ABIS=("armeabi-v7a" "arm64-v8a" "x86" "x86_64")
        API=21

        for ABI in "${ABIS[@]}"; do
          echo "=== Building for $ABI ==="

          # zlib
          mkdir -p build-zlib-$ABI
          cd zlib
          cmake -B ../build-zlib-$ABI -S . \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=$ABI \
            -DANDROID_PLATFORM=android-$API \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
            -DCMAKE_ANDROID_PAGE_SIZE=16384
          cmake --build ../build-zlib-$ABI -- -j$(nproc)
          cd ..

          # libpng
          mkdir -p build-libpng-$ABI
          cd libpng-1.6.40
          cmake -B ../build-libpng-$ABI -S . \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=$ABI \
            -DANDROID_PLATFORM=android-$API \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
            -DCMAKE_ANDROID_PAGE_SIZE=16384 \
            -DZLIB_LIBRARY=$(pwd)/../build-zlib-$ABI/libz.a \
            -DZLIB_INCLUDE_DIR=$(pwd)/../build-zlib-$ABI/
          cmake --build ../build-libpng-$ABI -- -j$(nproc)

          mkdir -p ../build-libpng-$ABI/include
          cp *.h ../build-libpng-$ABI/include/
          cp ../build-libpng-$ABI/pnglibconf.h ../build-libpng-$ABI/include/
          cd ..

          # FreeType
          mkdir -p build-freetype-$ABI
          cd build-freetype-$ABI
          cmake ../freetype \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=$ABI \
            -DANDROID_PLATFORM=android-$API \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
            -DCMAKE_ANDROID_PAGE_SIZE=16384 \
            -DFT_WITH_ZLIB=ON \
            -DFT_WITH_PNG=ON \
            -DFT_WITH_BZIP2=ON \
            -DZLIB_LIBRARY=$(pwd)/../build-zlib-$ABI/libz.a \
            -DZLIB_INCLUDE_DIR=$(pwd)/../build-zlib-$ABI \
            -DPNG_LIBRARY=$(pwd)/../build-libpng-$ABI/libpng16.a \
            -DPNG_PNG_INCLUDE_DIR=$(pwd)/../build-libpng-$ABI/include
          cmake --build . --config Release -- -j$(nproc)
          cd ..

          # HarfBuzz
          mkdir -p build-harfbuzz-$ABI
          cd build-harfbuzz-$ABI
          cmake ../harfbuzz \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=$ABI \
            -DANDROID_PLATFORM=android-$API \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
            -DCMAKE_ANDROID_PAGE_SIZE=16384 \
            -DHB_HAVE_FREETYPE=ON \
            -DFREETYPE_LIBRARY=$(pwd)/../build-freetype-$ABI/objs/.libs/libfreetype.a \
            -DFREETYPE_INCLUDE_DIRS=$(pwd)/../freetype/include \
            -DHB_HAVE_PNG=ON \
            -DPNG_LIBRARY=$(pwd)/../build-libpng-$ABI/libpng16.a \
            -DPNG_PNG_INCLUDE_DIR=$(pwd)/../build-libpng-$ABI/include
          cmake --build . --config Release -- -j$(nproc)
          cd ..

          # Collect headers and libs
          mkdir -p output/lib/$ABI \
                   output/include/freetype \
                   output/include/harfbuzz \
                   output/include/png \
                   output/include/zlib

          cp -r freetype/include/* output/include/freetype/
          cp -r harfbuzz/src/*.h output/include/harfbuzz/
          cp -r libpng-1.6.40/png.h output/include/png/
          cp -r zlib/*.h output/include/zlib/
          cp build-libpng-$ABI/include/pnglibconf.h output/include/png/

          cp build-freetype-$ABI/objs/.libs/*.a output/lib/$ABI/ || true
          cp build-harfbuzz-$ABI/src/*.a output/lib/$ABI/ || true
          cp build-libpng-$ABI/libpng16.a output/lib/$ABI/
          cp build-zlib-$ABI/libz.a output/lib/$ABI/
        done

    - name: Create ZIP
      run: zip -r font-libs-android-full.zip output

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: font-libs-android-full
        path: font-libs-android-full.zip
