name: Build FreeType + HarfBuzz + PNG/Zlib + MSDFGen for Android (Matrix ABIs, fPIC, 16KB page)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-font-libs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [armeabi-v7a, arm64-v8a, x86, x86_64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y git cmake ninja-build wget tar

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27c
        add-to-path: true

    - name: Fetch sources
      run: |
        git clone --depth=1 https://github.com/freetype/freetype.git freetype
        git clone --depth=1 https://github.com/harfbuzz/harfbuzz.git harfbuzz
        git clone --depth=1 https://github.com/madler/zlib.git zlib
        wget https://download.sourceforge.net/libpng/libpng-1.6.40.tar.gz -O libpng.tar.gz
        tar xf libpng.tar.gz

    # --- Existing builds for zlib, libpng, FreeType, HarfBuzz ---
    - name: Build zlib
      run: |
        mkdir -p build-zlib-${{ matrix.abi }}
        cd zlib
        cmake -B ../build-zlib-${{ matrix.abi }} -S . \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=${{ matrix.abi }} \
          -DANDROID_PLATFORM=android-21 \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_SHARED_LIBS=OFF \
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
          -DCMAKE_ANDROID_PAGE_SIZE=16384 \
          -DCMAKE_MINIMUM_REQUIRED_VERSION=3.22
        cmake --build ../build-zlib-${{ matrix.abi }} -- -j$(nproc)
        cd ..

    - name: Build libpng
      run: |
        mkdir -p build-libpng-${{ matrix.abi }}
        cd libpng-1.6.40
        cmake -B ../build-libpng-${{ matrix.abi }} -S . \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=${{ matrix.abi }} \
          -DANDROID_PLATFORM=android-21 \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_SHARED_LIBS=OFF \
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
          -DCMAKE_ANDROID_PAGE_SIZE=16384 \
          -DCMAKE_MINIMUM_REQUIRED_VERSION=3.22 \
          -DZLIB_LIBRARY=$(pwd)/../build-zlib-${{ matrix.abi }}/libz.a \
          -DZLIB_INCLUDE_DIR=$(pwd)/../build-zlib-${{ matrix.abi }}
        cmake --build ../build-libpng-${{ matrix.abi }} -- -j$(nproc)
        mkdir -p ../build-libpng-${{ matrix.abi }}/include
        cp *.h ../build-libpng-${{ matrix.abi }}/include/
        cp ../build-libpng-${{ matrix.abi }}/pnglibconf.h ../build-libpng-${{ matrix.abi }}/include/
        cd ..

    - name: Build FreeType
      run: |
        mkdir -p build-freetype-${{ matrix.abi }}
        cd build-freetype-${{ matrix.abi }}
        cmake ../freetype \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=${{ matrix.abi }} \
          -DANDROID_PLATFORM=android-21 \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_SHARED_LIBS=OFF \
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
          -DCMAKE_ANDROID_PAGE_SIZE=16384 \
          -DCMAKE_MINIMUM_REQUIRED_VERSION=3.22 \
          -DFT_WITH_ZLIB=ON \
          -DFT_WITH_PNG=ON \
          -DFT_WITH_BZIP2=ON \
          -DZLIB_LIBRARY=$(pwd)/../build-zlib-${{ matrix.abi }}/libz.a \
          -DZLIB_INCLUDE_DIR=$(pwd)/../build-zlib-${{ matrix.abi }} \
          -DPNG_LIBRARY=$(pwd)/../build-libpng-${{ matrix.abi }}/libpng16.a \
          -DPNG_PNG_INCLUDE_DIR=$(pwd)/../build-libpng-${{ matrix.abi }}/include
        cmake --build . --config Release -- -j$(nproc)
        cd ..

    - name: Build HarfBuzz
      run: |
        mkdir -p build-harfbuzz-${{ matrix.abi }}
        cd build-harfbuzz-${{ matrix.abi }}
        cmake ../harfbuzz \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=${{ matrix.abi }} \
          -DANDROID_PLATFORM=android-21 \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_SHARED_LIBS=OFF \
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
          -DCMAKE_ANDROID_PAGE_SIZE=16384 \
          -DCMAKE_MINIMUM_REQUIRED_VERSION=3.22 \
          -DHB_HAVE_FREETYPE=ON \
          -DFREETYPE_LIBRARY=$(find ../build-freetype-${{ matrix.abi }} -name "libfreetype.a" | head -n1) \
          -DFREETYPE_INCLUDE_DIRS=$(pwd)/../freetype/include \
          -DHB_HAVE_PNG=ON \
          -DPNG_LIBRARY=$(pwd)/../build-libpng-${{ matrix.abi }}/libpng16.a \
          -DPNG_PNG_INCLUDE_DIR=$(pwd)/../build-libpng-${{ matrix.abi }}/include
        cmake --build . --config Release -- -j$(nproc)
        cd ..

    - name: Collect headers and libraries
      run: |
        mkdir -p output/lib/${{ matrix.abi }} \
                 output/include/freetype \
                 output/include/harfbuzz \
                 output/include/png \
                 output/include/zlib 

        # Headers
        cp -r freetype/include/* output/include/freetype/
        cp -r harfbuzz/src/*.h output/include/harfbuzz/
        cp -r libpng-1.6.40/png.h output/include/png/
        cp -r zlib/*.h output/include/zlib/

        # Generated Build Headers
        cp build-libpng-${{ matrix.abi }}/include/pnglibconf.h output/include/png/

        # Static libraries
        FT_LIB=$(find build-freetype-${{ matrix.abi }} -name "libfreetype.a" | head -n1)
        HB_LIB=$(find build-harfbuzz-${{ matrix.abi }} -name "libharfbuzz.a" | head -n1)

        cp "$FT_LIB" output/lib/${{ matrix.abi }}/
        cp "$HB_LIB" output/lib/${{ matrix.abi }}/
        cp build-libpng-${{ matrix.abi }}/libpng16.a output/lib/${{ matrix.abi }}/
        cp build-zlib-${{ matrix.abi }}/libz.a output/lib/${{ matrix.abi }}/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: font-libs-android-${{ matrix.abi }}
        path: output
