name: Build FreeType + HarfBuzz + PNG/Zlib + MSDFGen for Android (Matrix ABIs, fPIC, 16KB page)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-font-libs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [armeabi-v7a, arm64-v8a, x86, x86_64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y git cmake ninja-build wget tar

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27c
        add-to-path: true

    - name: Fetch sources
      run: |
        git clone --depth=1 https://github.com/freetype/freetype.git freetype
        git clone --depth=1 https://github.com/harfbuzz/harfbuzz.git harfbuzz
        git clone --depth=1 https://github.com/madler/zlib.git zlib
        git clone --depth=1 https://github.com/Chlumsky/msdfgen.git msdfgen
        wget https://download.sourceforge.net/libpng/libpng-1.6.40.tar.gz -O libpng.tar.gz
        tar xf libpng.tar.gz

    # --- Build zlib ---
    - name: Build zlib
      run: |
        mkdir -p build-zlib-${{ matrix.abi }}
        cd build-zlib-${{ matrix.abi }}
        cmake ../zlib \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=${{ matrix.abi }} \
          -DANDROID_PLATFORM=android-21 \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_SHARED_LIBS=OFF \
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
          -DCMAKE_ANDROID_PAGE_SIZE=16384 \
          -DCMAKE_INSTALL_PREFIX=$(pwd)/../install
        cmake --build . -- -j$(nproc)
        cmake --install .
        cd ..

    # --- Build libpng ---
    - name: Build libpng
      run: |
        mkdir -p build-libpng-${{ matrix.abi }}
        cd libpng-1.6.40
        cmake -B ../build-libpng-${{ matrix.abi }} -S . \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=${{ matrix.abi }} \
          -DANDROID_PLATFORM=android-21 \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_SHARED_LIBS=OFF \
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
          -DCMAKE_ANDROID_PAGE_SIZE=16384 \
          -DZLIB_LIBRARY=$(pwd)/../build-zlib-${{ matrix.abi }}/libz.a \
          -DZLIB_INCLUDE_DIR=$(pwd)/../install/include \
          -DCMAKE_INSTALL_PREFIX=$(pwd)/../install
        cmake --build ../build-libpng-${{ matrix.abi }} -- -j$(nproc)
        cmake --install ../build-libpng-${{ matrix.abi }}
        cd ..

    # --- Build FreeType ---
    - name: Build FreeType
      run: |
        mkdir -p build-freetype-${{ matrix.abi }}
        cd build-freetype-${{ matrix.abi }}
        cmake ../freetype \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=${{ matrix.abi }} \
          -DANDROID_PLATFORM=android-21 \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_SHARED_LIBS=OFF \
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
          -DCMAKE_ANDROID_PAGE_SIZE=16384 \
          -DFT_WITH_ZLIB=ON \
          -DFT_WITH_PNG=ON \
          -DZLIB_LIBRARY=$(pwd)/../build-zlib-${{ matrix.abi }}/libz.a \
          -DZLIB_INCLUDE_DIR=$(pwd)/../install/include \
          -DPNG_LIBRARY=$(pwd)/../build-libpng-${{ matrix.abi }}/libpng16.a \
          -DPNG_PNG_INCLUDE_DIR=$(pwd)/../install/include \
          -DCMAKE_INSTALL_PREFIX=$(pwd)/../install
        cmake --build . -- -j$(nproc)
        cmake --install .
        cd ..

    # --- Build HarfBuzz ---
    - name: Build HarfBuzz
      run: |
        mkdir -p build-harfbuzz-${{ matrix.abi }}
        cd build-harfbuzz-${{ matrix.abi }}
        cmake ../harfbuzz \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=${{ matrix.abi }} \
          -DANDROID_PLATFORM=android-21 \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_SHARED_LIBS=OFF \
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
          -DCMAKE_ANDROID_PAGE_SIZE=16384 \
          -DHB_HAVE_FREETYPE=ON \
          -DFREETYPE_LIBRARY=$(pwd)/../install/lib/libfreetype.a \
          -DFREETYPE_INCLUDE_DIRS=$(pwd)/../install/include/freetype2 \
          -DHB_HAVE_PNG=ON \
          -DPNG_LIBRARY=$(pwd)/../install/lib/libpng16.a \
          -DPNG_PNG_INCLUDE_DIR=$(pwd)/../install/include \
          -DCMAKE_INSTALL_PREFIX=$(pwd)/../install
        cmake --build . -- -j$(nproc)
        cmake --install .
        cd ..

    # --- Build MSDFGen ---
    - name: Build MSDFGen
      run: |
        mkdir -p build-msdfgen-${{ matrix.abi }}
        cd build-msdfgen-${{ matrix.abi }}
        cmake ../msdfgen \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=${{ matrix.abi }} \
          -DANDROID_PLATFORM=android-21 \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_SHARED_LIBS=OFF \
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
          -DCMAKE_ANDROID_PAGE_SIZE=16384 \
          -DMSDFGEN_USE_FREETYPE=ON \
          -DMSDFGEN_DISABLE_SVG=ON \
          -DMSDFGEN_DISABLE_PNG=ON \
          -DMSDFGEN_CORE_ONLY=ON \
          -DMSDFGEN_USE_SKIA=OFF \
          -DMSDFGEN_BUILD_STANDALONE=OFF \
          -DFREETYPE_LIBRARY=$(pwd)/../install/lib/libfreetype.a \
          -DFREETYPE_INCLUDE_DIRS=$(pwd)/../install/include/freetype2 \
          -DCMAKE_INSTALL_PREFIX=$(pwd)/../install
        cmake --build . -- -j$(nproc)
        cmake --install .
        cd ..

    # --- Upload artifact ---
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: font-libs-android-${{ matrix.abi }}
        path: install
